<?php
/**
 * Emit the eight WordPress auth salts as a PHP file.
 *
 * The shipped wp-config had all eight literally set to
 * "put your unique phrase here", which makes every auth cookie and nonce
 * forgeable by anyone who has seen a WordPress tutorial. Regenerating them is
 * not optional.
 *
 * By default the values are random and written once to the data dir, so they
 * survive redeploys and nobody gets logged out. Set SALT_SEED to any fixed
 * string to derive them deterministically instead — useful when there is no
 * persistent volume and you still want stable logins across restarts.
 */

declare( strict_types = 1 );

$keys = [
	'AUTH_KEY', 'SECURE_AUTH_KEY', 'LOGGED_IN_KEY', 'NONCE_KEY',
	'AUTH_SALT', 'SECURE_AUTH_SALT', 'LOGGED_IN_SALT', 'NONCE_SALT',
];

$seed = getenv( 'SALT_SEED' ) ?: '';

echo "<?php\n// Generated by gen-salts.php — do not commit.\n";
foreach ( $keys as $k ) {
	$v = $seed
		? hash_hmac( 'sha256', $k, $seed )
		: bin2hex( random_bytes( 32 ) );
	printf( "define( %s, %s );\n", var_export( $k, true ), var_export( $v, true ) );
}
