#!/usr/bin/env bash
#
# Rebuilds theme/assets/mts-styles.css from mytapestore-redesign/src/styles.
#
# Sibling of mytapestore-shopify/build-css.sh. Same source, same exact-parity
# contract, different render target. The design is defined in exactly one place
# — mytapestore-redesign/src/styles — and both stores are generated from it.
# Never hand-edit the output; edit the source and re-run.
#
# Why parity holds here, same as on Shopify: this theme loads NO vendor
# stylesheet. functions.php dequeues everything else, so mts-styles.css is the
# only CSS on the page, nothing rewrites the root font-size, and 1rem is the
# browser default 16px — exactly what the React app was authored against.
# Therefore rem values ship VERBATIM and the build fails if anything would
# rescale them.
#
# Usage: mytapestore-wordpress/scripts/build-css.sh
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
SRC="$ROOT/mytapestore-redesign/src/styles"
PUBLIC="$ROOT/mytapestore-redesign/public"
FONTS="$PUBLIC/fonts/fonts.css"
THEME="$HERE/../theme"
OUT="$THEME/assets/mts-styles.css"
OVERRIDES="$THEME/assets/mts-wordpress-overrides.css"

# The design's COMPONENT-STATE layer, ~109KB, currently living in the Shopify
# theme. It is not a Shopify shim: it holds .colban__img, the entire filter
# panel (.filt__body/.filt__check/.filt__chev/.filt__count/.filt__dot), the
# mobile collection bar, blog, account and cart-quantity styling. The React
# source does not contain these rules because React expressed those states in
# JSX instead of CSS, so a build from src/styles alone renders those components
# unstyled — which is exactly what happened.
#
# It contains no Liquid and no url(), so it is portable as-is. Referenced in
# place rather than copied, to keep one source of truth for both stores.
SHARED="$ROOT/mytapestore-shopify/theme/assets/mts-shopify-overrides.css"

# main.jsx: tokens, base. Then App.jsx, in its own import order.
# Reordering changes which rule wins, which changes the design.
ORDER=(tokens base header home product-card footer ui collection product cart checkout industries pages chat)

for f in "${ORDER[@]}"; do
  [ -f "$SRC/$f.css" ] || { echo "missing: $SRC/$f.css" >&2; exit 1; }
done
[ -f "$FONTS" ] || { echo "missing: $FONTS" >&2; exit 1; }

# --- sync the assets the CSS and templates reference -------------------------
mkdir -p "$THEME/assets"
for d in fonts img; do
  rsync -a --delete "$PUBLIC/$d/" "$THEME/assets/$d/"
done
echo "synced assets/{fonts,img} from mytapestore-redesign/public"

python3 - "$SRC" "$FONTS" "$OUT" "$OVERRIDES" "$THEME" "$SHARED" "${ORDER[@]}" <<'PY'
import re, sys, pathlib

src, fonts, out, overrides, theme, shared, *order = sys.argv[1:]
src, theme = pathlib.Path(src), pathlib.Path(theme)

HEADER = """/* GENERATED by mytapestore-wordpress/scripts/build-css.sh — do not edit by hand.
   Source: mytapestore-redesign/src/styles/*.css. Edit there and re-run.

   EXACT-PARITY CONTRACT
   Every colour, font-size, radius and space below is byte-for-byte what the
   React redesign ships, and byte-for-byte what the Shopify theme ships. rem
   values are NOT converted: this theme loads no vendor stylesheet (functions.php
   dequeues them), so the root font-size is the browser default 16px and a rem
   means here exactly what it means there. Never add a rule that sets a root
   font-size — it would rescale the entire store. The build fails if you do.

   Cascade order matches the React import order (main.jsx, then App.jsx). */
"""


def asset_urls(css):
    """Rewrite absolute Vite paths to theme-relative ones.

    Unlike Shopify's flat assets/ directory, WordPress keeps the tree, so
    /img/site/grain.png simply becomes img/site/grain.png — resolved relative
    to this stylesheet at theme/assets/mts-styles.css.
    """
    def sub(m):
        path = m.group(1).strip()
        if path.startswith(('data:', 'http://', 'https://', '//', '#')):
            return m.group(0)
        return "url(%s)" % path.lstrip('/')
    return re.sub(r"""url\(\s*['"]?([^)'"]+?)['"]?\s*\)""", sub, css)


pieces = [HEADER]

# fonts first — @font-face must be parsed before anything asks for the family.
pieces.append('\n/* ================= fonts.css ================= */\n')
pieces.append(asset_urls(pathlib.Path(fonts).read_text(encoding='utf-8')))

for name in order:
    css = (src / f'{name}.css').read_text(encoding='utf-8')
    pieces.append(f'\n/* ================= {name}.css ================= */\n')
    pieces.append(asset_urls(css))

# Shared component-state layer (see the note in the shell above). Appended
# after the ported sheets so it can refine them, before the WordPress-only file.
shared_path = pathlib.Path(shared)
shared_css = ''
if shared_path.exists():
    shared_css = shared_path.read_text(encoding='utf-8')
    pieces.append('\n/* ================= component-states.css ================= */\n')
    pieces.append(asset_urls(shared_css))

# Hand-written WordPress-only additions: states WooCommerce renders in markup
# that the React app expressed in JSX. Appended last so it can override.
ov_path = pathlib.Path(overrides)
if ov_path.exists():
    pieces.append('\n/* ================= wordpress-overrides.css ================= */\n')
    pieces.append(ov_path.read_text(encoding='utf-8'))

text = ''.join(pieces)

# --- guard 1: nothing may set a root font-size -------------------------------
root_fs = re.findall(r'(?:^|[},])\s*(?::root|html)\s*\{[^}]*font-size[^}]*\}', text)
if root_fs:
    sys.exit('root font-size set in the bundle — this rescales every rem:\n  '
             + '\n  '.join(s.strip()[:120] for s in root_fs))

# --- guard 2: rem count must survive the build untouched ---------------------
REM = r'(?<![\w.-])-?\d*\.?\d+rem\b'
source_rem = sum(len(re.findall(REM, p.read_text(encoding='utf-8')))
                 for p in [pathlib.Path(fonts)] + [src / f'{n}.css' for n in order])
ov_rem = len(re.findall(REM, ov_path.read_text(encoding='utf-8'))) if ov_path.exists() else 0
ov_rem += len(re.findall(REM, shared_css))
out_rem = len(re.findall(REM, text))
if out_rem != source_rem + ov_rem:
    sys.exit(f'rem count changed: source {source_rem}+{ov_rem} -> output {out_rem}. '
             'Values must ship verbatim.')

# --- guard 3: the token block must survive verbatim --------------------------
for token in ('--brand:        #df3c22', '--ink:      #1f1f1f', '--f-body:    "Inter"'):
    if token not in text:
        sys.exit(f'design token altered or missing: {token!r}')

# --- guard 4: no PHP may leak into a stylesheet ------------------------------
if re.search(r'<\?php|<\?=', text):
    sys.exit('PHP tag in CSS — this file is served as a static asset.')

# --- guard 5: every referenced asset must actually exist ---------------------
# Shopify fails loudly on a missing asset_url; WordPress just serves a 404 and
# the font silently falls back to a system face. Catch it at build time instead.
missing = sorted({u for u in re.findall(r"url\(([^)]+)\)", text)
                  if not u.startswith(('data:', 'http', '//', '#'))
                  and not (theme / 'assets' / u).exists()})
if missing:
    sys.exit('referenced assets missing from the theme:\n  ' + '\n  '.join(missing[:20]))

pathlib.Path(out).parent.mkdir(parents=True, exist_ok=True)
pathlib.Path(out).write_text(text, encoding='utf-8')

stats = [
    ('bytes',         format(len(text), ',')),
    ('design tokens', len(re.findall(r'^\s*--[a-z0-9-]+:', text, re.M))),
    ('rem values',    '%d (verbatim)' % out_rem),
    ('font-size',     len(re.findall(r'font-size\s*:', text))),
    ('color',         len(re.findall(r'(?<![-a-z])color\s*:', text))),
    ('border-radius', len(re.findall(r'border-radius\s*:', text))),
    ('line-height',   len(re.findall(r'line-height\s*:', text))),
    ('letter-spacing', len(re.findall(r'letter-spacing\s*:', text))),
    ('@font-face',    len(re.findall(r'@font-face', text))),
    ('@media',        len(re.findall(r'@media', text))),
]
print('wrote %s' % out)
for label, value in stats:
    print('  %-14s: %s' % (label, value))
PY
