#!/usr/bin/env bash
#
# Is the theme safe to put on mytapestore.com.au right now?
#
# Run this before every live deploy. It exits non-zero if anything would break
# the store, so it can gate a deployment rather than merely inform one.
#
#   scripts/preflight-live.sh
#
# WHAT IT IS CHECKING FOR, AND WHY EACH ONE EARNED ITS PLACE
#
# The cutover is THEME-ONLY: this theme goes onto the live install and the live
# database, plugins, orders and payment credentials all stay. That shape makes
# most of the usual migration risks disappear — no data to move, no prices to
# reconcile, Stripe already connected. What it leaves is a small number of ways
# this theme could hurt a store it has never met, and those are what this checks.
#
# Every check below corresponds to something that was actually found in this
# codebase, not to a generic checklist.

set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
THEME="$HERE/theme"
FAIL=0
WARN=0

red()   { printf '\033[31m%s\033[0m\n' "$*"; }
green() { printf '\033[32m%s\033[0m\n' "$*"; }
amber() { printf '\033[33m%s\033[0m\n' "$*"; }
head_() { printf '\n\033[1m%s\033[0m\n' "$*"; }

pass() { green "  PASS  $*"; }
fail() { red   "  FAIL  $*"; FAIL=$((FAIL+1)); }
warn() { amber "  WARN  $*"; WARN=$((WARN+1)); }

head_ "1. Payment gateways cannot displace the real ones"
# The placeholders use the live store's own gateway ids on purpose, so the
# checkout renders identically here. On live, two gateways claiming `stripe`
# means a placeholder can take an order and move no money. The class guard is
# what stops that, so its absence is a hard fail.
if [ -f "$THEME/inc/payment-gateways.php" ]; then
  if grep -q "mts_real_gateway_present" "$THEME/inc/payment-gateways.php"; then
    pass "placeholders stand down when a real gateway class exists"
  else
    fail "payment-gateways.php has NO real-plugin guard — it would fight live Stripe/PayPal"
  fi
else
  pass "payment-gateways.php removed entirely"
fi

head_ "2. Functional plugin CSS survives the stylesheet purge"
# The theme dequeues every vendor stylesheet; that is the parity contract. But
# Stripe's checkout CSS positions the card fields, and without it the store
# cannot take money.
for handle in wc-stripe-upe-classic wc-stripe-blocks-checkout-style select2; do
  if grep -q "'$handle'" "$THEME/functions.php"; then
    pass "allowlisted: $handle"
  else
    fail "NOT allowlisted: $handle — checkout styling would break on live"
  fi
done

head_ "3. No credentials anywhere in the theme"
# Keys belong in wp-config.php on the server. Anything in the theme is in git and
# in every deploy artefact.
#
# ONE FILE IS EXEMPT: MTS-API-KEYS.php.
#
# It is generated by scripts/write-api-keys.sh so the HANDOVER ARCHIVE arrives
# working, because the package has to install without asking whoever receives it
# to hand-edit wp-config.php. That was a deliberate call, so it is a WARN and not
# a silent pass — the trade-off is real and should be visible on every run — but
# it does not block, and the guard stays a hard failure for every other file so a
# key cannot reach the theme by accident.
KEYFILE="MTS-API-KEYS.php"
CRED_RE="gsk_[A-Za-z0-9]{20}|pk\.[0-9a-f]{30}|sk_live_|AIza[0-9A-Za-z_-]{30}|ck_prv_[A-Za-z0-9]{20}"

STRAY="$(grep -rlE "$CRED_RE" "$THEME" 2>/dev/null | grep -v "/$KEYFILE$" || true)"

if [ -n "$STRAY" ]; then
  fail "a credential-shaped string is present in theme/ outside $KEYFILE"
  printf '%s\n' "$STRAY" | sed 's/^/        /'
else
  pass "no stray API keys in theme/"
fi

if [ -f "$THEME/$KEYFILE" ]; then
  warn "$KEYFILE ships live keys INSIDE the theme (deliberate, for handover)"
  if [ -f "$THEME/.htaccess" ] && grep -q "MTS-API-KEYS" "$THEME/.htaccess" 2>/dev/null; then
    pass "  .htaccess denies HTTP access to it"
  else
    fail "  .htaccess is missing or does not cover it — the keys are web-readable if PHP stops executing"
  fi
  if grep -q "defined( 'ABSPATH' ) || exit" "$THEME/$KEYFILE" 2>/dev/null; then
    pass "  direct-request guard present"
  else
    fail "  no ABSPATH guard in $KEYFILE"
  fi
else
  pass "no keys defined in the theme (wp-config.php route)"
fi

# Any OTHER file defining a key is still the original hard failure.
if grep -rq "define( 'MTS_GROQ_KEY'" "$THEME" --exclude="$KEYFILE" 2>/dev/null \
   || grep -rq "define( 'MTS_LOCATIONIQ_KEY'" "$THEME" --exclude="$KEYFILE" 2>/dev/null; then
  fail "a key is DEFINED somewhere other than $KEYFILE"
else
  pass "no key defined outside $KEYFILE"
fi

head_ "4. The demo runtime is not in the theme"
# 00-mts-demo.php forces noindex sitewide and repoints media at the preview CDN.
# It lives in the deploy bundle, not the theme, and must never travel to live.
if find "$THEME" -name '00-mts-demo.php' | grep -q .; then
  fail "the demo mu-plugin is inside theme/ — it would de-index the live store"
else
  pass "demo mu-plugin is not in the theme"
fi

head_ "5. The stylesheet builds and passes its own guards"
if "$HERE/scripts/build-css.sh" >/tmp/mts-preflight-css.log 2>&1; then
  pass "build-css.sh completed: $(grep -oE 'bytes *: *[0-9,]+' /tmp/mts-preflight-css.log | head -1)"
else
  fail "build-css.sh failed — see /tmp/mts-preflight-css.log"
fi

if [ -f "$THEME/assets/mts-styles.css" ]; then
  pass "mts-styles.css present ($(du -h "$THEME/assets/mts-styles.css" | cut -f1))"
else
  fail "mts-styles.css missing"
fi

head_ "6. PHP parses"
if command -v php >/dev/null 2>&1; then
  BAD=0
  while IFS= read -r f; do
    php -l "$f" >/dev/null 2>&1 || { fail "syntax error: ${f#$HERE/}"; BAD=1; }
  done < <(find "$THEME" -name '*.php')
  [ "$BAD" -eq 0 ] && pass "every PHP file parses"
else
  warn "php CLI not installed — syntax not checked here (CI should)"
fi

head_ "7. Things a human still has to decide"
# Not failures. They are judgement calls that should be made deliberately rather
# than discovered after the fact.
warn "Contact Form 7: 13 shortcodes live in imported page content — confirm CF7 stays active on live"
warn "AddressFinder: the live store pays for addressfinder-woo and this theme ships its own finder — pick one"
warn "Consent boxes are pre-ticked; add_filter( 'mts_consent_default', '__return_false' ) to un-tick"
warn "No staging run yet — this theme has never met the live plugin set"

printf '\n'
if [ "$FAIL" -gt 0 ]; then
  red "NOT READY — $FAIL blocking problem(s), $WARN decision(s) outstanding."
  exit 1
fi

green "SAFE TO DEPLOY — 0 blocking problems, $WARN decision(s) outstanding."
echo
echo "  Deploy with:  scripts/deploy-live.sh --dry-run     (then without it)"
exit 0
