#!/usr/bin/env bash
#
# Generate theme/MTS-API-KEYS.php from .env, so the handover zip carries working
# keys and the developer's only job is to upload the theme.
#
# WHY THE KEYS ARE INSIDE THE THEME AT ALL
#
# They were originally shipped as a separate wp-config.php snippet, which is the
# safer arrangement: wp-config.php sits above the web root and is never served.
# It was overruled — the package has to work on upload, without asking the
# developer to hand-edit a file most hosts hide behind SFTP. That is a
# reasonable call for a demo handover, so this makes the in-theme route as safe
# as it can be made rather than pretending the trade-off is not there.
#
# WHAT PROTECTS IT
#
#   1. defined( 'ABSPATH' ) || exit — the file does nothing if requested directly
#      while PHP is working.
#   2. theme/.htaccess denies HTTP access to it outright, which is what covers
#      the case PHP is NOT working. That is the actual risk: a server that stops
#      executing .php serves it as plain text, and the keys are then readable by
#      anyone. Apache and LiteSpeed both honour this; VentraIP runs LiteSpeed.
#   3. defined() || define() — wp-config.php still wins if the same constant is
#      set there, so moving the keys somewhere better later needs no edit here.
#   4. The file is gitignored and regenerated from .env, so a key never enters
#      version control.
#
# NEITHER KEY CAN GENERATE A BILL. Both are free tiers with no card on file, so
# the worst case of a leak is quota exhaustion and a rotation, not an invoice.
# Rotate both once the site is live regardless.
#
# Usage: scripts/write-api-keys.sh
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$HERE/.env"
OUT="$HERE/theme/MTS-API-KEYS.php"
HTA="$HERE/theme/.htaccess"

[ -f "$ENV_FILE" ] || { echo "missing $ENV_FILE" >&2; exit 1; }

# shellcheck disable=SC1090
set -a; . "$ENV_FILE"; set +a

: "${GROQ_API_KEY:=}"
: "${CHECKIFY_KEY:=}"

[ -n "$GROQ_API_KEY" ] || echo "  WARNING: GROQ_API_KEY empty — chat will stay on scripted answers" >&2
[ -n "$CHECKIFY_KEY" ] || echo "  WARNING: CHECKIFY_KEY empty — street autocomplete will stay off" >&2

cat > "$OUT" <<PHP
<?php
/**
 * MY TAPE STORE — API KEYS.  KEEP THIS FILE PRIVATE.
 * ==================================================
 *
 * Loaded automatically by functions.php. There is NOTHING TO CONFIGURE — upload
 * the theme, activate it, and both features below are live.
 *
 * WHAT THESE SWITCH ON
 *
 *   MTS_GROQ_KEY       The chat assistant's language model. Without it the chat
 *                      widget still works but answers only from its built-in
 *                      script — which is exactly why the assistant appeared to
 *                      "not answer anything" before this build. It was never
 *                      broken; it had no key.
 *
 *   MTS_CHECKIFY_KEY   Street-line autocomplete at checkout. Without it the
 *                      street field is an ordinary text input. Suburb, state and
 *                      postcode autocomplete either way — those are matched from
 *                      a file inside this theme and need no key and no network.
 *
 * COST: both are free tiers with NO CARD ON FILE. Neither can produce a bill.
 *   Groq      1,000 requests / 200,000 tokens a day. The theme caps each visitor
 *             at 20 replies an hour so one person cannot drain the day's supply.
 *   Checkify  The endpoint this theme uses is UNMETERED — verified against this
 *             account: units_used stayed at 0 across autocomplete calls and moved
 *             only when /autocomplete-details was called once. The theme never
 *             calls that endpoint, so the 250-unit monthly allowance is never
 *             touched. The real limit is 30 requests/minute across the whole
 *             site, which the theme stays under by debouncing 220ms, requiring 5
 *             characters, and caching each answer for 24 hours.
 *
 * MOVING THESE SOMEWHERE SAFER (recommended once live)
 *
 * Cut the two define() lines into wp-config.php, above "That's all, stop
 * editing!", then delete this file. The guards below mean wp-config.php wins
 * automatically, so nothing else needs changing. wp-config.php sits above the
 * web root and is never served, which is strictly safer than any file inside a
 * theme directory.
 *
 * ROTATE BOTH KEYS once the site is live — they were transmitted over chat
 * during development, which is not a channel either should have travelled on.
 *   Groq:     https://console.groq.com/keys
 *   Checkify: https://checkify.com.au  ->  dashboard  ->  API keys
 *
 * Generated by scripts/write-api-keys.sh from .env — do not hand-edit.
 */

// Refuse to do anything if requested directly rather than loaded by WordPress.
defined( 'ABSPATH' ) || exit;

// defined() first, so a value set in wp-config.php always takes precedence.
defined( 'MTS_GROQ_KEY' )     || define( 'MTS_GROQ_KEY', '${GROQ_API_KEY}' );
defined( 'MTS_CHECKIFY_KEY' ) || define( 'MTS_CHECKIFY_KEY', '${CHECKIFY_KEY}' );
PHP

chmod 600 "$OUT"

# The protection that matters when PHP is NOT executing. Written as both <Files>
# (Apache 2.2 / LiteSpeed) and <FilesMatch> under a version guard so it is
# correct on either.
cat > "$HTA" <<'HTACCESS'
# Deny HTTP access to the API key file.
#
# functions.php loads it through PHP, which does not go through the web server,
# so this costs the theme nothing. What it buys is the case that actually leaks
# credentials: a server that stops executing .php and serves it as plain text.
<FilesMatch "^MTS-API-KEYS\.php$">
  <IfModule mod_authz_core.c>
    Require all denied
  </IfModule>
  <IfModule !mod_authz_core.c>
    Order allow,deny
    Deny from all
  </IfModule>
</FilesMatch>
HTACCESS

echo "  wrote theme/MTS-API-KEYS.php   ($(wc -c < "$OUT" | tr -d ' ') bytes, chmod 600)"
echo "  wrote theme/.htaccess          (denies HTTP access to it)"
echo "  MTS_GROQ_KEY     : ${GROQ_API_KEY:0:7}…  (${#GROQ_API_KEY} chars)"
echo "  MTS_CHECKIFY_KEY : ${CHECKIFY_KEY:0:7}…  (${#CHECKIFY_KEY} chars)"
