#!/usr/bin/env bash
#
# Rebuilds theme/assets/mts-styles.css.liquid from mytapestore-redesign/src/styles.
#
# The whole point of this script is EXACT visual parity with the React redesign:
# same colours, same font sizes, same spacing, same everything. Two rules follow
# from that, and both are enforced below rather than trusted.
#
#   1. rem values ship VERBATIM. This theme is purpose-built — no vendor
#      stylesheet is loaded alongside it — so nothing rewrites the root font
#      size and 1rem is the browser default 16px, exactly as in the React app.
#      (The HooknLoop theme had to convert every rem to px because Suruchi set
#      html{font-size:62.5%}, which rendered 17px body text at 10.6px. That
#      hazard does not exist here, and converting anyway would risk rounding
#      drift.) The script FAILS if anything in the bundle sets a root font-size,
#      because that is the one change that would silently rescale the whole site.
#
#   2. The cascade order matches the React import order exactly — main.jsx loads
#      tokens then base, then App.jsx loads the per-area sheets in source order.
#      Reordering changes which rule wins, which changes the design.
#
# Served as .liquid so asset_url resolves inside @font-face and the grain URL.
#
# Usage: mytapestore-shopify/build-css.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/mytapestore-redesign/src/styles"
FONTS="$ROOT/mytapestore-redesign/public/fonts/fonts.css"
OUT="$ROOT/mytapestore-shopify/theme/assets/mts-styles.css.liquid"
OVERRIDES="$ROOT/mytapestore-shopify/theme/assets/mts-shopify-overrides.css"

# main.jsx: tokens, base. Then App.jsx, in its own import order.
ORDER=(tokens base header home product-card footer ui collection product cart checkout industries pages chat)

for f in "${ORDER[@]}"; do
  [ -f "$SRC/$f.css" ] || { echo "missing: $SRC/$f.css" >&2; exit 1; }
done
[ -f "$FONTS" ] || { echo "missing: $FONTS" >&2; exit 1; }

python3 - "$SRC" "$FONTS" "$OUT" "$OVERRIDES" "${ORDER[@]}" <<'PY'
import re, sys, pathlib

src, fonts, out, overrides, *order = sys.argv[1:]
src = pathlib.Path(src)

HEADER = """/* GENERATED by mytapestore-shopify/build-css.sh — do not edit by hand.
   Source: mytapestore-redesign/src/styles/*.css. Edit there and re-run.

   EXACT-PARITY CONTRACT
   Every colour, font-size, radius and space below is byte-for-byte what the
   React redesign ships. rem values are NOT converted: this theme loads no
   vendor stylesheet, so the root font-size is the browser default (16px) and
   a rem means here exactly what it means there. Never add a rule that sets a
   root font-size — it would rescale the entire store. The build fails if you do.

   Cascade order matches the React import order (main.jsx, then App.jsx). */
"""

def asset_urls(css):
    """Point url(...) at flattened theme assets. Shopify's assets/ is flat, so
    /img/site/grain.png becomes mts-grain.png etc."""
    def sub(m):
        path = m.group(1)
        name = path.rsplit('/', 1)[-1]
        if '/img/site/' in path and '/cat/' not in path and '/industry/' not in path and '/banners/' not in path:
            name = 'mts-' + name
        elif '/banners/' in path:
            name = 'mts-' + name
        elif '/fonts/' in path:
            pass                      # font files keep their names
        return "url({{ '%s' | asset_url }})" % name
    return re.sub(r"""url\(['"]?([^)'"]+)['"]?\)""", sub, css)

pieces = [HEADER]

# fonts first — @font-face must be parsed before anything asks for the family.
pieces.append('\n/* ================= fonts.css ================= */\n')
pieces.append(asset_urls(pathlib.Path(fonts).read_text(encoding='utf-8')))

for name in order:
    css = (src / f'{name}.css').read_text(encoding='utf-8')
    pieces.append(f'\n/* ================= {name}.css ================= */\n')
    pieces.append(asset_urls(css))

# Hand-written Shopify-only additions (cart/variant states Liquid needs that the
# React app expressed in JSX). Appended last so it can override the port.
ov_path = pathlib.Path(overrides)
if ov_path.exists():
    pieces.append('\n/* ================= shopify-overrides.css ================= */\n')
    pieces.append(ov_path.read_text(encoding='utf-8'))

text = ''.join(pieces)

# --- guard 1: nothing may set a root font-size -------------------------------
# This is the single change that would silently rescale every rem in the bundle
# and break the exact-size guarantee this file exists to provide.
root_fs = re.findall(r'(?:^|[},])\s*(?::root|html)\s*\{[^}]*font-size[^}]*\}', text)
if root_fs:
    sys.exit('root font-size set in the bundle — this rescales every rem:\n  '
             + '\n  '.join(s.strip()[:120] for s in root_fs))

# --- guard 2: rem count must survive the build untouched ---------------------
source_rem = 0
for p in [pathlib.Path(fonts)] + [src / f'{n}.css' for n in order]:
    source_rem += len(re.findall(r'(?<![\w.-])-?\d*\.?\d+rem\b', p.read_text(encoding='utf-8')))
out_rem = len(re.findall(r'(?<![\w.-])-?\d*\.?\d+rem\b', text))
ov_rem = len(re.findall(r'(?<![\w.-])-?\d*\.?\d+rem\b',
                        ov_path.read_text(encoding='utf-8'))) if ov_path.exists() else 0
if out_rem != source_rem + ov_rem:
    sys.exit(f'rem count changed: source {source_rem}+{ov_rem} -> output {out_rem}. '
             'Values must ship verbatim.')

# --- guard 3: the token block must survive verbatim --------------------------
# The brand colour is the thing most likely to get "helpfully" adjusted.
for token in ('--brand:        #df3c22', '--ink:      #1f1f1f', '--f-body:    "Inter"'):
    if token not in text:
        sys.exit(f'design token altered or missing: {token!r}')

# --- guard 4: only asset_url Liquid is legal in a .liquid stylesheet ---------
# A stray {% ... %} anywhere makes the WHOLE stylesheet fail to render and the
# store silently loses every style.
stray = [m.group(0) for m in re.finditer(r'\{%.*?%\}|\{\{.*?\}\}', text)
         if 'asset_url' not in m.group(0)]
if stray:
    sys.exit('Liquid tag(s) in CSS — the stylesheet will not render:\n  '
             + '\n  '.join(stray[:10]))

pathlib.Path(out).write_text(text, encoding='utf-8')

print(f'wrote {out}')
print(f'  bytes        : {len(text):,}')
print(f'  rem values   : {out_rem} (verbatim)')
print(f'  @font-face   : {len(re.findall(r"@font-face", text))}')
print(f'  @keyframes   : {len(re.findall(r"@keyframes", text))}')
print(f'  media queries: {len(re.findall(r"@media", text))}')
print(f'  asset refs   : {len(re.findall(r"asset_url", text))}')
PY
