#!/usr/bin/env bash
#
# Rebuilds theme/assets/hnl-redesign.css.liquid from storefront/src/styles.
#
# Two things this script exists to get right, both of which broke the theme
# when the bundle was assembled by hand:
#
#   1. fonts.css must be first. It was left out of the first build, so DM Sans
#      never loaded and the whole site fell back to a system font.
#
#   2. Every rem must become px. Suruchi sets
#          html { font-size: calc(var(--font-body-size) * 62.5%) }
#      so 1rem is 10px, not 16px. The React CSS is authored against a 16px
#      root, so shipping its rem values renders everything at 62.5% of the
#      intended size — 17px body text came out at 10.6px. Overriding the root
#      would break Suruchi's own rules on product and collection pages, so the
#      conversion happens here instead and the two stylesheets stay independent.
#      rem inside @media queries is NOT converted: media queries resolve
#      against the initial 16px root, not the html element's font-size.
#
# mobile.css is last because it is a deliberate override layer, and the
# Shopify-only overrides are appended after everything.
#
# Usage: shopify/build-css.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/storefront/src/styles"
OUT="$ROOT/shopify/theme/assets/hnl-redesign.css.liquid"
OVERRIDES="$ROOT/shopify/theme/assets/hnl-shopify-overrides.css"

ORDER=(fonts tokens base header hero slides sections film floating pages product industries cartdrawer mobile)

for f in "${ORDER[@]}"; do
  [ -f "$SRC/$f.css" ] || { echo "missing: $SRC/$f.css" >&2; exit 1; }
done

python3 - "$SRC" "$OUT" "$OVERRIDES" "${ORDER[@]}" <<'PY'
import re, sys, pathlib

src, out, overrides, *order = sys.argv[1:]
src = pathlib.Path(src)

HEADER = """/* GENERATED by shopify/build-css.sh — do not edit by hand.
   Source: storefront/src/styles/*.css. Edit there and re-run the script.

   NOTE ON UNITS
   Suruchi sets html{font-size:calc(var(--font-body-size) * 62.5%)}, i.e. 1rem
   = 10px. This bundle was authored against a 16px root, so every rem has been
   converted to its 16px-equivalent px value. Do not reintroduce rem here — it
   will render at 62.5% of the intended size. Suruchi's own stylesheets keep
   their rem units and their 10px root; the two no longer interact.

   Served as .liquid so asset_url resolves inside @font-face. */
"""

def rem_to_px(css):
    """Convert rem to px at a 16px root, skipping @media preludes.

    A media query's rem resolves against the initial root font-size, never the
    html element's own — so converting there would move every breakpoint."""
    out_parts, pos = [], 0
    for m in re.finditer(r'@media[^{]*\{', css):
        out_parts.append(_convert(css[pos:m.start()]))
        out_parts.append(m.group(0))          # prelude left untouched
        pos = m.end()
    out_parts.append(_convert(css[pos:]))
    return ''.join(out_parts)

def _convert(chunk):
    return re.sub(
        r'(?<![\w.-])(-?\d*\.?\d+)rem\b',
        lambda m: f'{round(float(m.group(1)) * 16, 2):g}px',
        chunk,
    )

pieces = [HEADER]
for name in order:
    css = (src / f'{name}.css').read_text(encoding='utf-8')
    if name == 'fonts':
        # Point @font-face at the theme asset rather than the Vite /fonts path.
        css = re.sub(r"url\(['\"]?[^)'\"]*?([\w.-]+\.woff2)['\"]?\)",
                     r"url({{ '\1' | asset_url }})", css)
    pieces.append(f'\n/* ================= {name}.css ================= */\n')
    pieces.append(rem_to_px(css))

# The overrides file is appended verbatim — it is hand-written against this
# theme, not ported — so the rem->px pass above never touches it. That makes a
# stray rem here silently render at 62.5% of its intended size, which is exactly
# the bug this whole script exists to prevent. Fail loudly instead.
ov = pathlib.Path(overrides).read_text(encoding='utf-8')
ov_rem = re.findall(r'(?<![\w.-])-?\d*\.?\d+rem\b', re.sub(r'@media[^{]*\{', '', ov))
if ov_rem:
    sys.exit(f'rem in {overrides}: {ov_rem}\n'
             'That file is not unit-converted. Use px (1rem = 16px).')

pieces.append('\n' + ov)
text = ''.join(pieces)

# The output is served as .liquid, so Liquid parses the whole file — including
# comments. A stray {% ... %} anywhere (a CSS comment mentioning a Liquid tag
# was the real case) makes the entire stylesheet fail to render, and the site
# silently loses every style. Only the asset_url substitutions above are legal.
stray = [m.group(0) for m in re.finditer(r'\{%.*?%\}|\{\{.*?\}\}', text)
         if 'asset_url' not in m.group(0)]
if stray:
    sys.exit('Liquid tag(s) in CSS — the stylesheet will not render:\n  '
             + '\n  '.join(stray[:10]))

pathlib.Path(out).write_text(text, encoding='utf-8')

leftover = re.findall(r'(?<![\w.-])-?\d*\.?\d+rem\b', re.sub(r'@media[^{]*\{', '', text))
print(f'wrote {out}')
print(f'  bytes            : {len(text)}')
print(f'  rem outside media: {len(leftover)}')
print(f'  keyframes        : {len(re.findall(r"@keyframes", text))}')
PY
